name: "Setup node/pnpm and install dependencies"
description: "Sets up Node.js, pnpm and all dependencies"

runs:
  using: composite
  steps:
    - name: Read .tool-versions
      uses: marocchino/tool-versions-action@v1
      id: versions

    - name: Use pnpm 8.x
      uses: pnpm/action-setup@v2
      with:
        version: ${{ steps.versions.outputs.pnpm }}
        run_install: false

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.versions.outputs.nodejs }}
        cache: "pnpm"

    - name: Install NPM dependencies
      shell: bash
      run: pnpm install
