# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 11:10
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title', label='Titel')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(label='Absatz')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bild')), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(label='Bild'), icon='grip', label='Bildgalerie', template='blocks/gallery.html')))),
        ),
    ]
