# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 11:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160617_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='body',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='column1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='column2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='skills',
            field=wagtail.wagtailcore.fields.StreamField((('skills', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='Bezeichnung', required=False), icon='stack', label='Skills', template='blocks/skills.html')),), default=''),
            preserve_default=False,
        ),
    ]
