# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:20
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160626_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='column1',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Spalte 1 (Briefing)'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='column2',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Spalte 2 (Lösungsansatz)'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='lead',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='skills',
            field=wagtail.wagtailcore.fields.StreamField((('skills', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.CharBlock(label='Bezeichnung', required=False), icon='code', label='Skills', template='blocks/skills.html')),)),
        ),
    ]
