# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:25
from __future__ import unicode_literals

from django.db import migrations
import projects.models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160626_1220'),
    ]

    operations = [
        
    ]
