# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:46
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projects', '0009_auto_20160626_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='skills',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='skill_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='projects.SkillTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
