# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160626_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
