# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectpage_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
