language: python
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - psql -c 'create database schaermu_ch;' -U postgres
  - export TEST_DB=$DB
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - coverage run ./manage.py test --with-coverage --cover-package schaermu_ch,common,contact,projects,home
after_success: coveralls
