language: python
python:
  - "3.5"
  - "3.5-dev"
  - "nightly"
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - psql -c 'create database schaermu_ch;' -U postgres
  - export TEST_DB=$DB
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - py.test --cov projects --cov contact --cov home --cov common
after_success: coveralls
