language: python
python:
  - "3.5"
env:
  - DB=sqlite
  - DB=postgres
before_script:
  - psql -c 'create database schaermu_ch;' -U postgres
  - export TEST_DB=$DB
  - export AWS_ACCESS_KEY_ID=foobar
  - export AWS_SECRET_ACCESS_KEY=foobar
  - export S3_BUCKET=schaermuch
  - export GOOGLE_SERVICE_PRIVATE_KEY=foobar
install:
  - if [[ $DB == postgres ]]; then pip install -q psycopg2; fi
  - pip install -q -r requirements.txt
  - pip install -q pytest pytest-django pytest-cov coveralls
script:
  - py.test --cov projects --cov contact --cov home --cov common
after_success: coveralls
