FROM mcr.microsoft.com/playwright:v1.53.0-noble

COPY . /app
WORKDIR /app

# install pnpm
RUN npm install -g pnpm

# setup dependencies & playwright
RUN pnpm install
RUN pnpm exec playwright install

# run tests
ENTRYPOINT ["pnpm", "exec", "playwright", "test"]