#!/bin/sh
TEST_DB=sqlite ptw --onpass "osascript -e \"display notification \\\"Tests passed!\\\" with title \\\"schaermu-ch\\\"\""
  --onfail "osascript -e \"display notification \\\"Tests failed!\\\" with title \\\"schaermu-ch\\\"\""
