#!/bin/sh
ptw --onpass "osascript -e \"display notification \\\"Tests passed!\\\" with title \\\"schaermu-ch\\\"\""
  --onfail "osascript -e \"display notification \\\"Tests failed!\\\" with title \\\"schaermu-ch\\\"\""
