# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformpage',
            name='head',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='thank_you_head',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactformpage',
            name='intro',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactformpage',
            name='thank_you_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
