# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160616_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformpage',
            name='head',
        ),
    ]
