# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('home', '0007_auto_20160614_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='portrait_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
