# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160616_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='url_github',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='url_linkedin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='homepage',
            name='url_stackoverflow',
            field=models.CharField(default='', max_length=250),
        ),
    ]
