# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160616_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='url_github',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_linkedin',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='url_stackoverflow',
        ),
    ]
